### ISSUE TITLE
UDF support

### ISSUE THREAD

**Issue by mamiao** [mutable-org/mutable#6]
Hi,

Is there any plan to support UDF? or it has already been implemented. 
Thanks

**Comment by ImmanuelHaffner** [comment]
Hi @mamiao,
we don't have support yet. No work in that regard is ongoing. However, we thought about UDF support by supporting embedding pre-compiled WebAssembly code within an SQL statement.

I think that would provide an efficient and very general solution. Nobody is currently working towards that goal, though. Let me know if you want to know more details ;)

**Comment by mamiao** [comment]
hi @ImmanuelHaffner ,

I am interested with it. I would like talk about that with you further ?  : )

**Comment by ImmanuelHaffner** [comment]
I'll send you a mail to arrange a video call :wink:

**Comment by mamiao** [comment]
mamiao000001@gmail.com Thanks
